# Generated by Django 3.1.2 on 2021-07-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measureITapp', '0004_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='lab_id',
            new_name='lab',
        ),
    ]
