# Generated by Django 3.1.2 on 2021-09-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measureITapp', '0005_auto_20210726_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=100)),
                ('output', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measureITapp.device')),
            ],
        ),
    ]
