# Generated by Django 3.1.2 on 2021-09-01 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measureITapp', '0006_measures'),
    ]

    operations = [
        migrations.AddField(
            model_name='measures',
            name='lab',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='measureITapp.alllabs'),
            preserve_default=False,
        ),
    ]
