# Generated by Django 3.1.2 on 2021-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measureITapp', '0007_measures_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='12345', max_length=100),
        ),
    ]
