# Generated by Django 3.1.2 on 2021-11-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measureITapp', '0008_device_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mac_adress',
        ),
        migrations.RemoveField(
            model_name='device',
            name='measure_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='units',
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(default='23', max_length=5),
        ),
    ]
