# Generated by Django 3.1.2 on 2021-11-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measureITapp', '0010_auto_20211116_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measureITapp.device')),
            ],
        ),
    ]
